### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ghost** [Blackoutburst/QuakeTest#2]
Hello, can you send me spigot 1.8 R3 file?

**Comment by Blackoutburst** [comment]
Hi, what do you mean exactly by the spigot 1.8 R3 file ?
Like if you want the spigot 1.8.8 also know as (1_8_R3) you can get it on the [official spigot website](https://www.spigotmc.org/threads/spigot-security-releases-—-1-8-8–1-18.537204/) using BuildTools or directly download it [here](https://getbukkit.org/get/hNiHm0tuqAg1Xg7w7zudk63uHr0xo48D)

If you talk about the plugin, I can effectively make a build but beware, this plugin is more a server core plugin for my community server than just a quake, so it may cause conflict with other plugins and some features aren't customisable but rather hard coded and the map selector will not work (/play)

**Comment by Blackoutburst** [comment]
Well, I'm still not sure of what you exactly asked but I removed the thing that really shouldn't be inside this plugin and created a release with the plugin jar file ¯\_(ツ)_/¯

[![Release](https://img.shields.io/github/release/Blackoutburst/QuakeCraft.svg)](https://github.com/Blackoutburst/QuakeCraft/releases)
